#!/usr/bin/env python3
from __future__ import annotations

import argparse
import errno
import fcntl
import os
import pty
import re
import select
import signal
import subprocess
import sys
import termios
import time
import tty

INJECT_BYTE = 0x14  # Ctrl+T
STOP_BYTE = 0x07  # Ctrl+G
TERM_GRACE_SECONDS = 2.0
INPUT_BURST_GRACE_SECONDS = 0.02
CTRL_MODIFIER_BIT = 4
LOCK_MODIFIER_BITS = 64 | 128

# Terminal capability replies are machine traffic generated by the terminal
# emulator in response to provider TUI queries. They are consumed by the
# supervisor and never forwarded to Claude.
TERMINAL_REPLY_RE = re.compile(rb"\x1b\[\?[0-9]+(?:;[0-9]+)*[cu]")
CSI_U_KEY_RE = re.compile(
    rb"\x1b\[(?P<code>[0-9]+)(?::[0-9]+(?::[0-9]+)?)?"
    rb"(?:;(?P<mods>[0-9]+)(?::(?P<event>[123]))?)?"
    rb"(?:;[0-9:]+)?u"
)


def classify_operator_input(data: bytes) -> tuple[bool, bool, bool, int]:
    inject = False
    stop = False
    unexpected = False
    terminal_replies = 0
    offset = 0

    while offset < len(data):
        value = data[offset]
        if value == INJECT_BYTE:
            inject = True
            offset += 1
            continue
        if value == STOP_BYTE:
            stop = True
            offset += 1
            continue

        if value == 0x1B:
            reply = TERMINAL_REPLY_RE.match(data, offset)
            if reply is not None:
                terminal_replies += 1
                offset = reply.end()
                continue

            key = CSI_U_KEY_RE.match(data, offset)
            if key is not None:
                code = int(key.group("code"))
                modifiers = int(key.group("mods") or b"1")
                event_type = int(key.group("event") or b"1")
                modifier_bits = modifiers - 1
                non_lock_bits = modifier_bits & ~LOCK_MODIFIER_BITS
                allowed_control = non_lock_bits == CTRL_MODIFIER_BIT
                if allowed_control and code in (ord("t"), ord("g")):
                    if event_type == 1:
                        if code == ord("t"):
                            inject = True
                        else:
                            stop = True
                    # Repeat/release events for the two harness chords are
                    # consumed but never forwarded or retriggered.
                    offset = key.end()
                    continue

            unexpected = True
            offset += 1
            continue

        unexpected = True
        offset += 1

    return inject, stop, unexpected, terminal_replies


def read_input_burst(fd: int) -> bytes:
    data = bytearray(os.read(fd, 4096))
    if not data:
        return b""
    deadline = time.monotonic() + INPUT_BURST_GRACE_SECONDS
    while len(data) < 65536:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        readable, _, _ = select.select([fd], [], [], remaining)
        if fd not in readable:
            break
        chunk = os.read(fd, 4096)
        if not chunk:
            break
        data.extend(chunk)
    return bytes(data)


def validate_probe_text(value: str) -> bytes:
    raw = value.encode("utf-8")
    if not raw:
        raise ValueError("empty")
    if any(value < 0x20 or value == 0x7F for value in raw):
        raise ValueError("control-byte")
    return raw


def reap_child_if_exited(pid: int) -> bool:
    try:
        waited = os.waitpid(pid, os.WNOHANG)
    except ChildProcessError:
        return True
    return waited != (0, 0)


def task_owned_session_processes(session_id: int) -> list[tuple[int, int]]:
    result = subprocess.run(
        ["/bin/ps", "-axo", "pid=,pgid="],
        check=True,
        capture_output=True,
        text=True,
    )
    processes: list[tuple[int, int]] = []
    for raw in result.stdout.splitlines():
        fields = raw.split()
        if len(fields) != 2:
            continue
        try:
            pid, pgid = map(int, fields)
        except ValueError:
            continue
        try:
            sid = os.getsid(pid)
        except (ProcessLookupError, PermissionError):
            continue
        if sid == session_id:
            processes.append((pid, pgid))
    return processes


def signal_task_owned_session(session_id: int, sig: signal.Signals) -> None:
    supervisor_pgid = os.getpgrp()
    groups = sorted(
        {
            pgid
            for _pid, pgid in task_owned_session_processes(session_id)
            if pgid > 0 and pgid != supervisor_pgid
        }
    )
    for pgid in groups:
        try:
            os.killpg(pgid, sig)
        except ProcessLookupError:
            pass


def wait_for_session_closed(pid: int, session_id: int, timeout: float) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        reap_child_if_exited(pid)
        if not task_owned_session_processes(session_id):
            return True
        time.sleep(0.02)
    reap_child_if_exited(pid)
    return not task_owned_session_processes(session_id)


def terminate_task_owned_session(pid: int, session_id: int) -> None:
    if session_id == os.getsid(0):
        raise RuntimeError("child shares supervisor session")
    signal_task_owned_session(session_id, signal.SIGTERM)
    if wait_for_session_closed(pid, session_id, TERM_GRACE_SECONDS):
        return
    signal_task_owned_session(session_id, signal.SIGKILL)
    if not wait_for_session_closed(pid, session_id, TERM_GRACE_SECONDS):
        raise RuntimeError("task-owned PTY session did not terminate")


def spawn_child(argv: list[str]) -> tuple[int, int]:
    master_fd, slave_fd = pty.openpty()
    ready_read, ready_write = os.pipe()
    pid = os.fork()
    if pid == 0:
        try:
            os.close(master_fd)
            os.close(ready_read)
            os.setsid()
            fcntl.ioctl(slave_fd, termios.TIOCSCTTY, 0)
            for target_fd in (0, 1, 2):
                if slave_fd != target_fd:
                    os.dup2(slave_fd, target_fd)
            if slave_fd > 2:
                os.close(slave_fd)
            os.write(ready_write, b"1")
            os.close(ready_write)
            os.execvpe(argv[0], argv, os.environ.copy())
        except BaseException:
            try:
                os.write(ready_write, b"0")
            except OSError:
                pass
            os._exit(127)

    os.close(slave_fd)
    os.close(ready_write)
    try:
        ready = os.read(ready_read, 1)
    finally:
        os.close(ready_read)
    if ready != b"1":
        try:
            os.waitpid(pid, 0)
        finally:
            os.close(master_fd)
        raise RuntimeError("child PTY session setup failed")
    return pid, master_fd


def supervise(argv: list[str], probe_text: str) -> int:
    if not argv:
        print("CLAUDE_TTY_SUPERVISOR_BLOCKED:COMMAND_REQUIRED", file=sys.stderr)
        return 64
    if not (sys.stdin.isatty() and sys.stdout.isatty()):
        print("CLAUDE_TTY_SUPERVISOR_BLOCKED:INTERACTIVE_TTY_REQUIRED", file=sys.stderr)
        return 2

    try:
        probe_bytes = validate_probe_text(probe_text)
    except ValueError as exc:
        print(f"CLAUDE_TTY_SUPERVISOR_BLOCKED:INVALID_PROBE_TEXT:{exc}", file=sys.stderr)
        return 64

    stdin_fd = sys.stdin.fileno()
    stdout_fd = sys.stdout.fileno()
    saved = termios.tcgetattr(stdin_fd)
    pid = -1
    master_fd = -1
    stop_seen = False
    probe_injected = False
    terminal_replies_consumed = 0
    blocked_reason: str | None = None

    try:
        pid, master_fd = spawn_child(argv)
        child_session = os.getsid(pid)
        if child_session == os.getsid(0):
            raise RuntimeError("child PTY session is not task-owned")

        tty.setraw(stdin_fd)
        os.write(
            stdout_fd,
            b"\r\n[CLROOM release probe: Ctrl+T injects the fixed probe; Ctrl+G ends observation; all other human input is blocked]\r\n",
        )

        while True:
            readable, _, _ = select.select([stdin_fd, master_fd], [], [])

            if master_fd in readable:
                try:
                    data = os.read(master_fd, 65536)
                except OSError as exc:
                    if exc.errno == errno.EIO:
                        data = b""
                    else:
                        raise
                if not data:
                    break
                os.write(stdout_fd, data)

            if stdin_fd in readable:
                data = read_input_burst(stdin_fd)
                if not data:
                    blocked_reason = "OPERATOR_TTY_EOF"
                    break

                inject, stop, unexpected, terminal_replies = classify_operator_input(data)
                terminal_replies_consumed += terminal_replies
                if unexpected:
                    blocked_reason = "UNEXPECTED_OPERATOR_INPUT"
                    break
                if inject:
                    if probe_injected:
                        blocked_reason = "PROBE_ALREADY_INJECTED"
                        break
                    os.write(master_fd, probe_bytes)
                    probe_injected = True
                if stop:
                    stop_seen = True
                    break

        if master_fd >= 0:
            try:
                os.close(master_fd)
            except OSError:
                pass
            master_fd = -1

        if pid > 0:
            try:
                terminate_task_owned_session(pid, child_session)
            except ProcessLookupError:
                pass

    finally:
        termios.tcsetattr(stdin_fd, termios.TCSADRAIN, saved)
        if master_fd >= 0:
            try:
                os.close(master_fd)
            except OSError:
                pass

    sys.stdout.write("\n")
    sys.stdout.flush()

    print(f"PROBE_INJECTED={'YES' if probe_injected else 'NO'}")
    print(f"TERMINAL_REPLIES_CONSUMED={terminal_replies_consumed}")
    print("HUMAN_BYTES_FORWARDED=0")
    print("SUBMIT_BYTES_FORWARDED=0")
    print("HARNESS_STOP_FORWARDED=0")

    if blocked_reason is not None:
        print(f"CLAUDE_TTY_SUPERVISOR_BLOCKED:{blocked_reason}", file=sys.stderr)
        return 3
    if not probe_injected:
        print("CLAUDE_TTY_SUPERVISOR_BLOCKED:PROBE_NOT_INJECTED", file=sys.stderr)
        return 4
    if not stop_seen:
        print("CLAUDE_TTY_SUPERVISOR_BLOCKED:PROVIDER_EXITED_BEFORE_HARNESS_STOP", file=sys.stderr)
        return 5

    print("CLAUDE_TTY_SUPERVISOR=PASS")
    print("TASK_PROCESS_SESSION_CLOSED=YES")
    return 0


def self_test() -> int:
    def expect_input(
        raw: bytes,
        expected: tuple[bool, bool, bool, int],
        label: str,
    ) -> None:
        observed = classify_operator_input(raw)
        if observed != expected:
            raise SystemExit(
                f"CLAUDE_TTY_SUPERVISOR_SELF_TEST_FAIL:TERMINAL_PROTOCOL_FILTER:{label}:"
                f"expected={expected}:observed={observed}"
            )

    expect_input(bytes([INJECT_BYTE]), (True, False, False, 0), "LEGACY_INJECT")
    expect_input(bytes([STOP_BYTE]), (False, True, False, 0), "LEGACY_STOP")
    expect_input(b"x", (False, False, True, 0), "PRINTABLE")
    expect_input(b"\r", (False, False, True, 0), "ENTER")
    expect_input(b"\n", (False, False, True, 0), "NEWLINE")
    expect_input(b"\x1b[A", (False, False, True, 0), "ARROW")
    expect_input(b"\x1b", (False, False, True, 0), "ESCAPE")

    kitty_flags = b"\x1b[?0u"
    da1 = b"\x1b[?64;1;2;4;6;17;18;21;22;52c"
    expect_input(kitty_flags, (False, False, False, 1), "KITTY_FLAGS_REPLY")
    expect_input(da1, (False, False, False, 1), "DA1_REPLY")
    expect_input(
        kitty_flags + da1 + bytes([INJECT_BYTE]),
        (True, False, False, 2),
        "REPLIES_PLUS_LEGACY_INJECT",
    )

    # Claude Code may enable Kitty keyboard disambiguation on the real terminal.
    # The two harness chords must still work without forwarding those key events.
    expect_input(b"\x1b[116;5u", (True, False, False, 0), "CSI_U_INJECT")
    expect_input(b"\x1b[103;5u", (False, True, False, 0), "CSI_U_STOP")
    expect_input(b"\x1b[116;5:3u", (False, False, False, 0), "CSI_U_RELEASE")
    expect_input(b"\x1b[120;5u", (False, False, True, 0), "CSI_U_OTHER_CTRL")
    expect_input(b"\x1b[116;3u", (False, False, True, 0), "CSI_U_ALT_T")

    if validate_probe_text("/frontend-design") != b"/frontend-design":
        raise SystemExit("CLAUDE_TTY_SUPERVISOR_SELF_TEST_FAIL:PROBE_TEXT")
    for unsafe in ("", "x\r", "x\n"):
        try:
            validate_probe_text(unsafe)
        except ValueError:
            pass
        else:
            raise SystemExit("CLAUDE_TTY_SUPERVISOR_SELF_TEST_FAIL:PROBE_CONTROL")

    split_group_child = """
import os
import signal
import time

child = os.fork()
if child == 0:
    os.setpgid(0, 0)
    signal.signal(signal.SIGHUP, signal.SIG_IGN)
    signal.signal(signal.SIGTERM, signal.SIG_IGN)
    time.sleep(30)
    raise SystemExit(0)

signal.signal(signal.SIGHUP, signal.SIG_IGN)
signal.signal(signal.SIGTERM, signal.SIG_IGN)
os.waitpid(child, 0)
"""
    pid, master_fd = spawn_child([sys.executable, "-c", split_group_child])
    try:
        session_id = os.getsid(pid)
        deadline = time.monotonic() + 2.0
        while time.monotonic() < deadline:
            groups = {pgid for _pid, pgid in task_owned_session_processes(session_id)}
            if len(groups) >= 2:
                break
            time.sleep(0.02)
        else:
            raise SystemExit("CLAUDE_TTY_SUPERVISOR_SELF_TEST_FAIL:SPLIT_PROCESS_GROUP")

        terminate_task_owned_session(pid, session_id)
        if task_owned_session_processes(session_id):
            raise SystemExit("CLAUDE_TTY_SUPERVISOR_SELF_TEST_FAIL:SESSION_RESIDUE")
    finally:
        try:
            os.close(master_fd)
        except OSError:
            pass

    print("CLAUDE_TTY_SUPERVISOR_SELF_TEST_PASS")
    return 0

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--probe-text")
    parser.add_argument("command", nargs=argparse.REMAINDER)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.self_test:
        return self_test()
    if args.probe_text is None:
        print("CLAUDE_TTY_SUPERVISOR_BLOCKED:PROBE_TEXT_REQUIRED", file=sys.stderr)
        return 64
    command = list(args.command)
    if command and command[0] == "--":
        command = command[1:]
    return supervise(command, args.probe_text)


if __name__ == "__main__":
    raise SystemExit(main())
